version: '3'
services:
  app:
    container_name: typescript
    restart: always
    build: .
    ports:
      - '3658:3658'
    environment:
     - DB_URL=mongodb://mongo:27017/auth
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"